### ISSUE TITLE
[BUG] Doesn't Work as Expected on the First Build

### ISSUE THREAD

**Issue by ilkersigirci** [Hugos68/vite-plugin-pagefind#34]
Firstly, thank you for this awesome work. I have tried to use this plugin on my Sveltekit project.  I have run `npm run build && npm run preview`. On the first run, the search functionality doesn't work although the script created `pagefind` in build and static directories. On the second run, the search is working as expected. Is this a bug or expected behaviour? Thanks.

- **First run**

![first_run_1](https://github.com/Hugos68/vite-plugin-pagefind/assets/39417966/3cffd5c6-35fe-42fd-8a99-d4ca79d86abe)
![first_run_2](https://github.com/Hugos68/vite-plugin-pagefind/assets/39417966/97dfe180-6a21-45b1-9f79-111821954eba)

- **Second run**
![second_run](https://github.com/Hugos68/vite-plugin-pagefind/assets/39417966/cdc0b8da-7103-447a-9071-d3446dc19bb3)

- My search component is the following

```svelte
<script>
	import { onMount } from 'svelte'
	import { page } from '$app/stores'
	import { PagefindUI } from '@pagefind/default-ui'
	import '@pagefind/default-ui/css/ui.css'
	import { title } from '$lib/config'

	onMount(() => {
		const pagefind = new PagefindUI({
			element: '#search',
			showSubResults: true,
			showImages: false,
			showEmptyFilters: false,
			autofocus: true,
			// sort: { date: "desc" },
			// bundlePath: "/pagefind/",
			processResult: function (result) {
				// Remove .html from result.url and result.raw_url
				result.url = result.url.replace(/\.html$/, '')
				result.raw_url = result.raw_url.replace(/\.html$/, '')

				return result
			}
		})
		pagefind.triggerSearch($page.url.searchParams.get('q'))
		const search_input = document.querySelector('#search input')

		search_input.addEventListener('input', (e) => {
			const search_params = new URLSearchParams(window.location.search)
			search_params.set('q', e.target.value)
			const new_url = `${window.location.pathname}?${search_params.toString()}`
			history.pushState(null, '', new_url)
		})
	})
</script>

<svelte:head>
	<title>Search {title}</title>
</svelte:head>

<div id="search" />
```

**Comment by Hugos68** [comment]
Hey @ilkersigirci, this is definitely not as expected, thanks for reporting this, could you share your Vite config so I can try and reproduce this issue? Thanks! Also please share what framework/project setup you are using, I have not tested every single framework out there.

**Comment by ilkersigirci** [comment]
@Hugos68  Thanks for the quick reply. The full repository can be found [here](https://github.com/ilkersigirci/my-blog/tree/feature/add-search). The `vite.config.ts` file is like below

```ts
import { sveltekit } from '@sveltejs/kit/vite'
import { defineConfig } from 'vitest/config'
import { pagefind } from 'vite-plugin-pagefind'

export default defineConfig({
	plugins: [sveltekit(), pagefind({ publicDir: 'static', buildDir: 'build' })],
	test: {
		include: ['src/**/*.{test,spec}.{js,ts}']
	}
})

```

**Comment by Hugos68** [comment]
Ok @ilkersigirci I've reproduced this issue, this isn't an issue with my plugin or pagefind but rather a issue with Vite's preview server, it's not really a good way to test build output.
The best way to test if your build runs properly is to do:
```bash
npx http-server build
# or pnpm
# pnpm dlx http-server build
```
This wil serve your app locally, for me it works first try without any problems. Let me know if that also is the case for you, this is what searching looks like after running the build and after that the command above:
![image](https://github.com/Hugos68/vite-plugin-pagefind/assets/63101006/cbd83531-8158-43b5-906d-eaf58c48950e)

**Comment by ilkersigirci** [comment]
Woow, I have tried that and it worked perfectly. Thanks.
