### ISSUE TITLE
A way to use this package without pagefind.json ?

### ISSUE THREAD

**Issue by Matthijz98** [Hugos68/vite-plugin-pagefind#50]
I just updated to the latest version and now the pagefind.json seems needed.
But i include pagefind and this package from a boilerplate astro plugin.
So it would love to not make the pagefind.json but pass the config somewhere in my plugin
Maybe by passing it in my astro.config.tsx (then i can do that from the index.ts of my plugin)
```
  vite: {
      plugins: [
          pagefind({MABE HERE FOR EXAMPLE})                            
```
Or when the config is not found just use the default options
Then only ``site`` would need a default option

**Comment by Hugos68** [comment]
This isn't possible, the reason it now uses a `.json` file is because of config mismatch between `dev` and `build` a single `json` file removes this inconsistency.

**Comment by hankertrix** [comment]
> This isn't possible, the reason it now uses a `.json` file is because of config mismatch between `dev` and `build` a single `json` file removes this inconsistency.

I think this is possible. I'll create a pull request in 2 to 3 weeks implementing this feature in a backwards-compatible manner.

**Comment by Hugos68** [comment]
@hankertrix That's awesome, I've assigned the issue to you.

**Comment by Hugos68** [comment]
@Matthijz98 The `.json` config has been completely moved in the first major version: 1.0. Just wanted to let you know.
