### ISSUE TITLE
Sveltekit build causing .html to be appended to url of every result

### ISSUE THREAD

**Issue by zachczx** [Hugos68/vite-plugin-pagefind#51]
Hello, I'm using Sveltekit with the Cloudflare adapter. I went ahead to implement all 3 points on the blog, installed this plugin, and for good measure shifted the /pagefind folder to the output /static folder (static assets that vite passes along to the eventual output folder). 

While running it in dev mode, the URLs of results come back with .html appended, whereas the actual routes should not come with them. Appreciate any advice please, thank you!

**Comment by Hugos68** [comment]
Hey @zachczx,

SvelteKit is actually the most tested framework for this plugin so it should absolutely work. I didn't have to mess with `.html` or anything so I think there is something wrong in your config. Sharing your `pagefind.json` would be appreciated. If it's possible it would be even better if your repository was publicly available so I can look at it myself.

**Comment by zachczx** [comment]
Thanks for the reply! My pagefind.json should be correct now, I did go through quite a bit of hairpulling to figure out these settings, I overthought everything and my previous settings were unnecessary (as described previously). 

`{
	"site": "build",
	"vite_plugin_pagefind": {
		"assets_dir": "static",
		"build_command": "npm run build",
		"dev_strategy": "lazy"
	}
}
`

The search results don't link properly in dev mode, as they come with a prefix route "/output/prerendered/pages/", but the live version is fine. 

The thing is in prod every result comes up with an appended filename .html. [Can be reproduced here](https://titude.app/search), with the [github repo here](https://github.com/zachczx/apptitude)

The URLs in prod work, but I thought it was odd, and I was thinking to just flag it out here in case. I did recall seeing an earlier issue raised and it being a pathing bug, but that was some time back.

But if that's an intended behavior don't mind me! Thanks much.

**Comment by Hugos68** [comment]
Thanks for the quicky reply alongside a reproduction. I tried cloning and running the dev server but was met with this error:
```cmd
error when starting dev server:
Error: Command failed: npm run build
6:38:08 PM [vite-plugin-svelte] You are using Svelte 5.0.0-next.155. Svelte 5 support is experimental, breaking changes can occur in any release until this notice is removed.
work in progress:
 - svelte-inspector is disabled until dev mode implements node to code mapping

6:38:09 PM [vite-plugin-svelte] src/routes/guides/+page.svelte:239:1 Unused CSS selector ".box-shadow"
6:38:09 PM [vite-plugin-svelte] src/routes/+layout.svelte:138:0 Using `<slot>` to render parent content is deprecated. Use `{@render ...}` tags instead
6:38:09 PM [vite-plugin-svelte] src/routes/todo/+page.svelte:72:5 `storeLearnButton` is updated, but is not declared with `$state(...)`. Changing its value will not correctly trigger updates
x Build failed in 8.38s
error during build:
[vite:css] [postcss] ENOENT: no such file or directory, open 'C:\pagefind\pagefind-ui.css'
file: C:/Users/hugok/repositories/apptitude/src/app.css:undefined:NaN
    at async open (node:internal/fs/promises:636:25)
    at async Object.readFile (node:internal/fs/promises:1246:14)
    at async Object.load (file:///C:/Users/hugok/repositories/apptitude/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:36419:25)
    at async loadImportContent (file:///C:/Users/hugok/repositories/apptitude/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9/node_modules/vite/dist/node/chunks/dep-Cde5FfFr.js:844:19)
    at async Promise.all (index 0)
    at async resolveImportId (file:///C:/Users/hugok/repositories/apptitude/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9/node_modules/vite/dist/node/chunks/dep-Cde5FfFr.js:800:27)
    at async parseStyles$1 (file:///C:/Users/hugok/repositories/apptitude/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9/node_modules/vite/dist/node/chunks/dep-Cde5FfFr.js:708:5)
    at async Object.Once (file:///C:/Users/hugok/repositories/apptitude/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9/node_modules/vite/dist/node/chunks/dep-Cde5FfFr.js:965:22)
    at async LazyResult.runAsync (C:\Users\hugok\repositories\apptitude\node_modules\.pnpm\postcss@8.4.38\node_modules\postcss\lib\lazy-result.js:261:11)
    at async compileCSS (file:///C:/Users/hugok/repositories/apptitude/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:36482:21)

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
 ELIFECYCLE  Command failed with exit code 1.
 ```
 I'll just remove that stylesheet for now but maybe something to look at.
 I'll get back at you once I figure out what could be the issue.

**Comment by Hugos68** [comment]
So I did some digging and the default UI just adds `.html`. (I personally don't use the Default UI).
However, the default UI allows you to process each result with a callback: https://pagefind.app/docs/ui/#process-result

This allows you to do the following:
```js
new PagefindUI({
	// ...
	processResult: (result) => {
		const url = result.url.replace('.html', '');
		result.url = url;
		return result;
	},
});
```

Which removes the `.html` if present.

The only problem with this is that when doing this the result appears twice:
```html
<div class="pagefind-ui__result-inner svelte-4xnkmf">
	<p class="pagefind-ui__result-title svelte-4xnkmf">
		<a class="pagefind-ui__result-link svelte-4xnkmf" href="/techtrippin">Tech Trippin'</a>
	</p>
	<div class="pagefind-ui__result-nested svelte-4xnkmf">
		<p class="pagefind-ui__result-title svelte-4xnkmf">
			<a class="pagefind-ui__result-link svelte-4xnkmf" href="/techtrippin.html">Tech Trippin'</a>
		</p>
		<p class="pagefind-ui__result-excerpt svelte-4xnkmf">
			Blind... Right Off a Tech Cliff. <mark>You're</mark> So Close... Yet So Far
		</p>
	</div>
</div>
```

This appears to be a bug with Pagefind as we have no control over the UI apart from that configuration options you give it (the vite plugin doesn't do anything that could affect this either). So I suggest opening up a ticket showcasing the double result when editing the `url` in the `processResult` option.

**Comment by zachczx** [comment]
I see, sorry to trouble you so much! I'll live with it for now since it doesn't affect the results, and the solution almost seems like a worse outcome. I wonder if this is something that breaks because of Svelte 5, so waiting a little is definitely an option. (Sorry I didn't realize my previous commits broke my stuff and made you clone my problematic code.)

**Comment by zachczx** [comment]
Closing this since this isn't a bug with vite-plugin-pagefind.

**Comment by Hugos68** [comment]
> Sorry I didn't realize my previous commits broke my stuff and made you clone my problematic code.

No worries, a broken repro is 100 times better than not a repro at all.
Yeah I'd say close this issue and maybe open one in the `pagefind` repo, if you do that, feel free to link to that issue here for future reference.
